/home/drew/Documents/GitHub/ShipDetection/scripts/Runall_shpDetection.sh "/home/drew/Documents/Data/BlackSea/toprocess" "/home/drew/Documents/Products/BlackSea" "BlackSea"
/home/drew/Documents/GitHub/ShipDetection/scripts/Runall_shpDetection.sh "/home/drew/Documents/Data/NortheastAtlantic/toprocess" "/home/drew/Documents/Products/NortheastAtlantic" "NortheastAtlantic"
/home/drew/Documents/GitHub/ShipDetection/scripts/Runall_shpDetection.sh "/home/drew/Documents/Data/NorthIndian/toprocess" "/home/drew/Documents/Products/NorthIndian" "NorthIndian"
/home/drew/Documents/GitHub/ShipDetection/scripts/Runall_shpDetection.sh "/home/drew/Documents/Data/NorthPacific/toprocess" "/home/drew/Documents/Products/NorthPacific" "NorthPacific"
/home/drew/Documents/GitHub/ShipDetection/scripts/Runall_shpDetection.sh "/home/drew/Documents/Data/SouthAtlantic/toprocess" "/home/drew/Documents/Products/SouthAtlantic" "SouthAtlantic"
/home/drew/Documents/GitHub/ShipDetection/scripts/Runall_shpDetection.sh "/home/drew/Documents/Data/SouthEastAsia/toprocess" "/home/drew/Documents/Products/SouthEastAsia" "SouthEastAsia"
/home/drew/Documents/GitHub/ShipDetection/scripts/Runall_shpDetection.sh "/home/drew/Documents/Data/SouthIndian/toprocess" "/home/drew/Documents/Products/SouthIndian" "SouthIndian"
